from __future__ import annotations

import sys
from pathlib import Path

from hetero1a import __version__ as hetero1a_version
from hetero2.pipeline import run_pipeline_v2
from hetero2.report import render_report_v2


def main() -> int:
    try:
        import rdkit  # noqa: F401
    except Exception:
        print('RDKit not installed; install extra "chem": pip install -e ".[dev,chem]"')
        return 1

    smiles = "CC(=O)OC1=CC=CC=C1C(=O)O"
    seed = 0
    timestamp = "2026-01-02T00:00:00+00:00"

    print("HETERO-2 demo: Aspirin")
    print("RDKit OK")
    print("Cycle Decoys via degree-preserving rewiring ...")
    pipeline = run_pipeline_v2(
        smiles,
        k_decoys=20,
        seed=seed,
        timestamp=timestamp,
        score_mode="mock",
        scores_input=None,
    )

    neg = pipeline.get("audit", {}).get("neg_controls", {})
    verdict = neg.get("verdict", "")
    method = neg.get("method", "")
    slack = neg.get("slack", "")
    warnings = pipeline.get("warnings", [])

    print(f"Audit ... Null quantiles method: {method}")
    print(f"FINAL VERDICT: {verdict} (slack={slack})")
    if warnings:
        print("Warnings:")
        for w in warnings:
            print(f"- {w}")

    out_path = Path("aspirin_report.md")
    assets_dir = out_path.with_name("aspirin_assets")
    render_report_v2(pipeline, out_path=str(out_path), assets_dir=assets_dir)
    print(f"Wrote {out_path} (assets in {assets_dir})")
    print(f"Generated by HETERO Screening Engine v{hetero1a_version}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
